# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy to testflight"
  lane :beta do
    sync_code_signing(type: "appstore")
    cocoapods
    build_app(scheme: "STU", workspace: "STU.xcworkspace", include_bitcode: true)
    upload_to_testflight
  end

  desc "Run all the tests!"
  lane :ci do
    cocoapods(clean_install: true)
    wkspc = "STU.xcworkspace"
    scan(workspace: wkspc, scheme: "STU")
    scan(workspace: wkspc, scheme: "STUCore")
  end
end
